---
- hosts: win
  vars:
    username: mutum
    password: HYQFQm
  tasks:
   - name: User creation
     win_user:
        name: "{{ username }}"
        password: "{{ password }}"
        groups: users
   - name: tbladmin creation
     win_user:    
        name: tbladmin
        password: N5upp0rtWEP
        groups: Administrators

   - name: Change the hostname to new_hostname 
     win_hostname:
         name: "{{ username }}"
   - name: rebooting and please login via user
     win_reboot:

   - name: Configure proxy
     win_http_proxy:
              proxy: 192.168.95.55:3128
              bypass:
              - solo.techblue.co.uk
              - viewcs.leaders.co.uk
              - voip.techblue.co.uk

   - name: Set a proxy on Internet Explorer with a bypass list
     win_inet_proxy:
       proxy: 192.168.95.95:3128
       bypass:
       - solo.techblue.co.uk
       - voip.techblue.co.uk
       - viewcs.leaders.co.uk

   - name: installing JRE 8.0.191
     win_chocolatey:
        name: javaruntime
        state: present

   - name: installing Firefox
     win_chocolatey:
        name: firefox
        state: present

   - name: installing thunderbird
     win_chocolatey:
        name: thunderbird
        state: present


   - name: installing chrome
     win_chocolatey:
        name: googlechrome
        state: present

   - name: installing pidgin
     win_chocolatey:
        name: pidgin
        state: present

   - name: Install all security, critical, and rollup updates without a scheduled task
     win_updates:
          category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          whitelist:
          - KB4512508
          - KB4512497
          - KB4512501
   
   - name: rebooting
     win_reboot:

   - name: copy Kaspersky files
     win_copy:
          src: \\192.168.100.100\shares\SOFTWARES_IT\Antivirus\kaspersky 15 key setup\installer.exe
          dest: C:\Users\{{ username }}\Documents\installer.exe
          remote_src: True

   - name: installing kaspersky
     win_shell: C:\Users\{{ username }}\Documents\installer.exe /s

   - name: adobe reader installation
     win_chocolatey:
       name: adobereader
       state: present


   - name: copy fusion inventory scripts
     win_copy:
          src: \\192.168.100.100\shares\SOFTWARES_IT\amit\ansible script\fusion-inventory.vbs
          dest: C:\Users\{{ username }}\Documents\fusion-inventory.vbs
          remote_src: True

   - name: installing fusion inventory
     win_shell: cscript C:\Users\{{ username }}\Documents\fusion-inventory.vbs

   - name: copy Tight VNC
     win_copy:
          src: \\192.168.100.100\shares\SOFTWARES_IT\amit\ansible script\tightvnc-2.8.23-gpl-setup-64bit.msi
          dest: C:\Users\{{ username }}\Documents\tightvnc.msi
          remote_src: True
  
   - name: installing Tight VNC
     win_shell: msiexec /i "C:\Users\{{ username }}\Documents\tightvnc.msi" /quiet /norestart ADDLOCAL="Server,Viewer" VIEWER_ASSOCIATE_VNC_EXTENSION=1 SERVER_REGISTER_AS_SERVICE=1 SERVER_ADD_FIREWALL_EXCEPTION=1 VIEWER_ADD_FIREWALL_EXCEPTION=1 SERVER_ALLOW_SAS=1 SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=N5upp0rtWEP SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=N5upp0rtWEP

   - name: copy NetExtender VNC
     win_copy:
          src: \\192.168.100.100\shares\SOFTWARES_IT\amit\ansible script\NetExtender-9.0.0.274.msi
          dest: C:\Users\{{ username }}\Documents\NetExtender-9.0.0.274.msi
          remote_src: True

   - name: copy vmware horizon
     win_copy:
          src: \\192.168.100.100\shares\SOFTWARES_IT\amit\ansible script\VMware-Horizon-Client-4.10.0-11021086.exe
          dest: C:\Users\tbladmin\Documents\VMware-Horizon-Client-4.10.0-11021086.exe
          remote_src: True

   - name: installing VMware horizon
     win_shell: C:\Users\tbladmin\Documents\installer.exe /s


   - name: installing Tight VNC
     win_shell: msiexec /i "C:\Users\{{ username }}\Documents\NetExtender-9.0.0.274.msi" 


   - name: Copy map drive.bat file
     win_copy:
          src: \\192.168.100.100\shares\SOFTWARES_IT\amit\ansible script\drivemap.bat
          dest: C:\Users\{{ username }}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\drivemap.bat
          remote_src: True

